// products.js
const allProducts = [
    { title: "Healing Is a gift by \"Alexandera vasiliu\"", page: "Products.html" },
    { title: "Great Gasby by \"F.Scott fizgerald\"", page: "Products.html" },
    { title: "Unleashed by \"Sydnie Short\"", page: "Products.html" },
    { title: "THe Nectar of Pain by \"Najwa Zebian\"", page: "Products.html" },
    { title: "The art of bieng alone by \" Renuka Gavrani\"", page: "Products.html" },
    { title: "Metamorphosis by \"Franz Kafka\"", page: "Products.html" },
    { title: "White Nights by \"Fydor Dostovoesky\"", page: "Products.html" },
    { title: "The moon by \"Kamilla Tolno\"", page: "Products.html" },
    { title: "Dont believe everything you think by \"Joseph Nguyen\"", page: "Products_2.html" },
    { title: "I used to have a plan by \"Alessandra Olanow\"", page: "Products_2.html" },
    { title: "Loneliness by \"Sydnie Short\"", page: "Products_2.html" },
    { title: "We dream of space by \"Najwa Zebian\"", page: "Products_2.html" },
    { title: "The Book Thief by \" Renuka Gavrani\"", page: "Products_2.html" },
    { title: "1984 by \"Franz Kafka\"", page: "Products_2.html" },
    { title: "THe secret history by \"Fydor Dostovoesky\"", page: "Products_2.html" },
    { title: "The GoldFinch by \"Kamilla Tolno\"", page: "Products_2.html" },
    { title: "Kill a mocking bird by \"Alexandera vasiliu\"", page: "Products_3.html" },
    { title: "Hand maid's tale by \"F.Scott fizgerald\"", page: "Products_3.html" },
    { title: "A little Life by \"Sydnie Short\"", page: "Products_3.html" },
    { title: "Why fish dont exist by \"Najwa Zebian\"", page: "Products_3.html" },
    { title: "The song achilles by \" George RR Martin\"", page: "Products_3.html" },
    { title: "The winds of winter by \"George RR Martin\"", page: "Products_3.html" },
    { title: "A game of thrones \"George RR Martin\"", page: "Products_3.html" },
    { title: "A dance with dragons \"George RR Martin\"", page: "Products_3.html" },
];